package com.rifters.riftedreader.util

object ReaderConstants {
    const val CONVEYOR_BUFFER_SIZE = 5
    const val CONVEYOR_CENTER_INDEX = 2
    const val CONVEYOR_UNLOCK_WINDOW = 2
    const val CONVEYOR_STEADY_TRIGGER_WINDOW = 3
    const val DEFAULT_PAGINATION_WINDOW_SIZE = 5
    const val SLIDING_WINDOW_BUFFER_WINDOW_COUNT = 5

    const val BOOKMARK_MATCH_CHAR_RADIUS = 200
    const val BOOKMARK_AUTOSAVE_DEBOUNCE_MS = 2_000L
    const val SCROLL_AUTOSAVE_DEBOUNCE_MS = 500L
    const val CALIBRE_SEARCH_DEBOUNCE_MS = 400L
    const val OFFSCREEN_SLICE_TIMEOUT_MS = 10_000L
    const val CONVEYOR_READY_TIMEOUT_MS = 10_000L
    const val CONVEYOR_SHIFT_THRESHOLD_PAGES = 2
    const val PENDING_NAVIGATION_TIMEOUT_MS = 1_200L
    const val PENDING_NAVIGATION_POLL_MS = 50L
    const val TOC_JUMP_MAX_READY_ATTEMPTS = 40
    const val TOC_JUMP_READY_CHECK_DELAY_MS = 50L
    const val WEBVIEW_MEASURED_LOAD_MAX_ATTEMPTS = 40
    const val WEBVIEW_MEASURED_LOAD_RETRY_DELAY_MS = 50L
    const val WINDOW_TRANSITION_COOLDOWN_MS = 300L
    const val BOUNDARY_DEDUPE_MS = 1_000L
    const val NAVIGATION_COOLDOWN_MS = 500L
    const val CONTENT_RELOAD_FADE_DURATION_MS = 150L
    const val MIN_HORIZONTAL_FLING_DISTANCE_PX = 64f
    const val MIN_HORIZONTAL_FLING_VELOCITY_PX_PER_SEC = 800f
    const val SCROLL_DISTANCE_THRESHOLD_RATIO = 0.25f
    const val TTS_PREP_MAX_ATTEMPTS = 5
    const val TTS_PREP_RETRY_DELAY_MS = 50L
    const val STREAMING_RETRY_MAX_ATTEMPTS = 2
    const val STREAMING_RETRY_DELAY_MS = 120L
    const val PAGINATOR_INITIALIZATION_DELAY_MS = 200L
    const val TTS_START_DELAY_MS = 200L
    const val STREAMING_FAILURE_TOAST_COOLDOWN_MS = 3_000L
    const val CONTROLS_AUTO_HIDE_MS = 3_500L
    const val CONTROLS_ANIMATION_DURATION_MS = 180L
    val IMAGE_BACKOFF_DELAYS_MS = longArrayOf(50L, 100L, 200L, 400L, 800L)
    const val DOWNLOAD_FILENAME_MAX_ATTEMPTS = 1_000
    const val DOWNLOAD_CONNECT_TIMEOUT_SECONDS = 10
    const val DOWNLOAD_READ_TIMEOUT_SECONDS = 60
    const val DOWNLOAD_WRITE_TIMEOUT_SECONDS = 10
}
